In [1]:
print(list(map(lambda x: x*x, [1, 2, 3])))

[1, 4, 9]


In [5]:
#Explain the purpose of the else block in a try-except-else construct.
#We can explain using a code that is given below
try:
    mark_1=int(input('Enter the mark_1: '))
    mark_2=int(input('Enter the mark_2: '))
    total_marks=mark_1+mark_2
except:
    print("Please enter your mark as integer")
else:
    print("Your total marks is: ", total_marks)

#else statement used to return the output

Enter the mark_1:  69
Enter the mark_2:  98


Your total marks is:  167


In [9]:
#Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.
import numpy as np
from numpy.random import randint as ri
matrix1=np.array(ri(5,15,9)).reshape(3,3)
matrix2=np.array(ri(5,15,9)).reshape(3,3)
print("First Matrix: \n", matrix1)
print("Second Matrix: \n", matrix2)

First Matrix: 
 [[ 5  7 11]
 [11  6 12]
 [10  7 14]]
Second Matrix: 
 [[12  8 14]
 [14 12  7]
 [10 13 10]]


In [21]:
concatenate_matrix1=np.concatenate((matrix1, matrix2), axis=0)
print("Concatenate Matrix along axis=0: \n", concatenate_matrix1)


Concatenate Matrix along axis=0: 
 [[ 5  7 11]
 [11  6 12]
 [10  7 14]
 [12  8 14]
 [14 12  7]
 [10 13 10]]


In [23]:
concatenate_matrix2=np.concatenate((matrix1, matrix2), axis=1)
print("Concatenate Matrix along axis=1: \n", concatenate_matrix2)

Concatenate Matrix along axis=1: 
 [[ 5  7 11 12  8 14]
 [11  6 12 14 12  7]
 [10  7 14 10 13 10]]
